name: scinterop
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - numpy
  - scipy
  - pandas
  - anndata
  - r-base>=4.4
  - r-seurat
  - r-anndata
  - r-matrix
  - r-qs
  - pip:
    - scinterop
